---
- name: Create a new Demo EC2 instance
  hosts: local
  connection: local
  gather_facts: False

  vars:
      region: ap-south-1
      instance_type: t2.micro
      ami: ami-041db4a969fe3eb68  # Amazon Linux
      keypair: 11Nov21 # pem file name

  vars_files:
     - pass.yml
  tasks:

    - name: Create an ec2 instance
      ec2:
         aws_access_key: "{{ access_key }}"
         aws_secret_key: "{{ secret_key }}"
         key_name: "{{ keypair }}"
         group: default  # security group name
         instance_type: "{{ instance_type}}"
         image: "{{ ami }}"
         wait: true
         region: "{{ region }}"
         count: 1  # default
         count_tag:
            Name: Unisys-Demo
         instance_tags:
            Name: Unisys-Demo
         vpc_subnet_id: subnet-037e3db5f092dd8b1
         assign_public_ip: yes
      register: ec2
