---
- hosts: webserver
  become: yes
  tasks:
  - name: Copy the website config file
    copy: src=proxy.conf dest=/etc/httpd/conf.d/proxy.conf

    notify:
    - Apache Restart

  handlers:
    - name: Apache Restart
      service: name=httpd state=restarted
