---
- hosts: webserver
  become: yes
  tasks:
  - name: manage packages
    package: name={{ item.name }} state={{ item.state }}
    with_items:
      - { name: tree, state: present }
      - { name: nmap, state: present }
      - { name: tomcat*, state: absent }
